### ISSUE TITLE
It's important!!!!!!!

### ISSUE THREAD

**Issue by rityak** [Taruu/mailproxy-with-utils#1]
Your project urgently needs to be rewritten in rust!
Rust is a multi-paradigm, high-level, general-purpose programming language that emphasizes performance, type safety, and concurrency. It enforces memory safety—ensuring that all references point to valid memory—without requiring the use of a garbage collector or reference counting present in other memory-safe languages. To simultaneously enforce memory safety and prevent concurrent data races, its "borrow checker" tracks the object lifetime of all references in a program during compilation. Rust is popular for systems programming but also has high-level features including some functional programming constructs.

**Comment by Taruu** [comment]
I'll do that when I write the version on intel 386
